[package]
name = "stardive"
description = "Reserved for future projects..."
version = "0.0.0"
edition = "2021"
authors = ["Noah <noahbuergler@proton.me"]
license = "GPL-3.0-or-later"
repository = "https://github.com/NQMVD/stardive"
documentation = "https://docs.rs/stardive"

[dependencies]
